name: flutter_temporizer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/sounds/

# Configuración del icono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  # Opcional: para iOS adaptativo
  # image_path_ios: "assets/images/icon_ios.png"
  # adaptive_icon_background: "#6C63FF"
  # adaptive_icon_foreground: "assets/images/icon_foreground.png"

# Configuración del splash screen
flutter_native_splash:
  color: "#5B6FD8"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  color_dark: "#5B6FD8"
  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: center
  android: true
  ios: true
  fullscreen: true
